# Generated by Django 3.2.7 on 2022-01-29 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(default='defusername', max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('pan', models.CharField(max_length=50, unique=True, verbose_name='pan')),
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('dob', models.DateField(verbose_name='dob')),
                ('gender', models.CharField(max_length=50, verbose_name='gender')),
                ('phoneno', models.CharField(max_length=10, verbose_name='phoneno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_no', models.CharField(default='253227578037', max_length=12)),
                ('balance', models.IntegerField()),
                ('acc_type', models.CharField(max_length=50)),
                ('open_date', models.DateField()),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('ifsc', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='fkbranch')),
                ('receiver_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiveracc', to='accounts.account')),
                ('sender_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderacc', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=50)),
                ('order_time', models.DateField()),
                ('order_status', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='fkcust')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_txt', models.CharField(max_length=200)),
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='fkacc')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='fkcust')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_no', models.AutoField(primary_key=True, serialize=False)),
                ('card_type', models.CharField(max_length=50)),
                ('credit_limit', models.IntegerField()),
                ('credit_used', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='fkacc')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='fkbranch'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='fkcustomer'),
        ),
    ]
