# Generated by Django 3.2.7 on 2022-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.CharField(default='225600650037', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_no',
            field=models.CharField(default='1329768734581382', max_length=16, primary_key=True, serialize=False),
        ),
    ]
