# Generated by Django 3.2.7 on 2022-02-06 07:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.CharField(default='247427400165', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_no',
            field=models.CharField(default=accounts.models.give_card, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='17872975499925', max_length=14, primary_key=True, serialize=False),
        ),
    ]
