# Generated by Django 3.2.7 on 2021-12-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_no', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('acc_type', models.CharField(max_length=50)),
                ('open_date', models.DateField()),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('ifsc', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan',
            field=models.CharField(max_length=50, unique=True, verbose_name='pan'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='fkbranch')),
                ('receiver_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiveracc', to='accounts.account')),
                ('sender_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderacc', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=50)),
                ('order_time', models.DateField()),
                ('order_status', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='fkcust')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_txt', models.CharField(max_length=200)),
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='fkacc')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='fkcust')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('card_no', models.AutoField(primary_key=True, serialize=False)),
                ('card_type', models.CharField(max_length=50)),
                ('credit_limit', models.IntegerField()),
                ('credit_used', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='fkacc')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='fkbranch'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='fkcustomer'),
        ),
    ]
