# Generated by Django 3.2.7 on 2022-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220129_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id',
            new_name='acc_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.CharField(default='303554995658', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_no',
            field=models.CharField(default='3281531827170957', max_length=16, primary_key=True, serialize=False),
        ),
    ]
