# Generated by Django 3.2.7 on 2022-02-06 07:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220206_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.CharField(default=accounts.models.acc_no, max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='92648970095748', max_length=14, primary_key=True, serialize=False),
        ),
    ]
