# Generated by Django 3.2.7 on 2022-01-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211220_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phoneno',
            field=models.CharField(default='9876543210', max_length=10, verbose_name='phoneno'),
            preserve_default=False,
        ),
    ]
