# Generated by Django 3.2.7 on 2022-02-28 06:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220226_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_ref',
            field=models.CharField(default=accounts.models.give_complaint_ref, max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_txt',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='17348112010788', max_length=14, primary_key=True, serialize=False),
        ),
    ]
